### ISSUE TITLE
Error: Can't scrape date. Please try again or submit issue to the github

### ISSUE THREAD

**Issue by dieg0almeida** [drawrowfly/instagram-scraper#13]
I have been used this package normally, but recently when i build my project on Heroku appear this error. Locally in my machine works, but in heroku doesn't works.

2020-06-09T21:03:41.098581+00:00 app[web.1]: Error: Can't scrape date. Please try again or submit issue to the github
2020-06-09T21:03:41.098583+00:00 app[web.1]:     at InstaTouch.extractData (/app/node_modules/instatouch/build/core/InstaTouch.js:369:27)
2020-06-09T21:03:41.098587+00:00 app[web.1]:     at async InstaTouch.startScraper (/app/node_modules/instatouch/build/core/InstaTouch.js:146:13)
2020-06-09T21:03:41.098588+00:00 app[web.1]:     at async promiseScraper (/app/node_modules/instatouch/build/entry.js:110:20)
2020-06-09T21:03:41.098588+00:00 app[web.1]:     at async Object.getInstagramFiles (/app/src/app/models/Cute.js:15:24)

Somebody help me?

**Comment by drawrowfly** [comment]
#12 lets keep it clean
