### ISSUE TITLE
InstaTouch Scraper StartedError: Can't scrape date. Please try again or submit issue to the github

### ISSUE THREAD

**Issue by valakhosravi** [drawrowfly/instagram-scraper#35]
On simple command like instatouch user [instagram page id] -m image
I get:
```
InstaTouch Scraper StartedError: Can't scrape date. Please try again or submit issue to the github
    at InstaTouch.extractData (/usr/local/lib/node_modules/instatouch/build/core/InstaTouch.js:372:27)
    at async InstaTouch.startScraper (/usr/local/lib/node_modules/instatouch/build/core/InstaTouch.js:149:13)
    at async promiseScraper (/usr/local/lib/node_modules/instatouch/build/entry.js:112:20)
    at async startScraper (/usr/local/lib/node_modules/instatouch/bin/cli.js:36:25)
```
and it stuck on:
`⠏ InstaTouch Scraper Started`

**Comment by drawrowfly** [comment]
Use proxy and session
