### ISSUE TITLE
InstaTouch Scraper StartedError: Can't scrape date.

### ISSUE THREAD

**Issue by briantstev** [drawrowfly/instagram-scraper#49]
Instatouch version 2.3.3
npm version 6.14.13

Briants-MacBook-Pro-2866:instascrap briant$ instatouch user adamar_digital -c 20 -d -s
⠏ InstaTouch Scraper StartedError: Can't scrape date. Please try again or submit issue to the github
    at InstaTouch.extractData (/usr/local/lib/node_modules/instatouch/build/core/InstaTouch.js:372:27)
    at async InstaTouch.startScraper (/usr/local/lib/node_modules/instatouch/build/core/InstaTouch.js:149:13)
    at async promiseScraper (/usr/local/lib/node_modules/instatouch/build/entry.js:112:20)
    at async startScraper (/usr/local/lib/node_modules/instatouch/bin/cli.js:36:25)
⠴ InstaTouch Scraper Started
![Screen Shot 2021-05-20 at 11 40 58](https://user-images.githubusercontent.com/35303128/118920250-4032c480-b960-11eb-88c5-dcefc5f05927.png)

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/instagram-scraper#get-session-id
